import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

type Target = { id: string; label: string; repository: string; source_repository: string; head_sha: string; kind: string; branch: string; pr?: number; base_branch?: string; base_sha?: string; checked_at: string; status: string; report?: string; error?: string };
type Index = { schema_version: string; checked_at: string; targets: Target[]; preferred_branch: string; analysis_repository: string; discovery_error?: string; publication_error?: string };
type Finding = { id: string; severity: string; message: string; file: string; line: number; scanners: string[]; rules: string[]; page: number };
type Detail = Finding & { origins: { scanner_family: string; rule: string; file: string; start_line: number; raw_artifact: string; observation_id: string }[]; source: string | null; source_start: number; source_url: string | null };
type Channel = { channel: string; name: string; class: string; status: string; findings: number | null; observation_count: number; reason: string; workflow: string };
type Report = { tooling_sha?: string; producer_run_attempt?: number; analyzed_sha: string; generated_at: string; status: string; finding_count: number; observation_count: number; channels: Channel[]; severities: Record<string, number>; producer_runs: { id: string; url: string }[]; publication_gate: { satisfied: boolean } };
const states: Record<string, string> = { current: 'Up to date', partial: 'Partial analysis', queued: 'Queued', scanning: 'Scanning', stale: 'Newer revision pending', failed: 'Analysis failed' };
const ranks: Record<string, number> = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3, INFO: 4, UNKNOWN: 5 };
async function json<T>(path: string, signal?: AbortSignal): Promise<T> {
  const compressed = await fetch(`${path}.gz`, { signal });
  if (compressed.ok) {
    if (compressed.headers.get('content-encoding') === 'gzip') return compressed.json();
    if (!compressed.body) throw new Error('Empty report response');
    return new Response(compressed.body.pipeThrough(new DecompressionStream('gzip'))).json();
  }
  // Uncompressed local fixtures remain usable without a separate development server.
  const r = await fetch(path, { signal }); if (!r.ok) throw new Error(`Report unavailable (${r.status}). Try again after the next publication.`); return r.json();
}
function route() { const p = new URLSearchParams(location.hash.slice(1)); return { target: p.get('target') || '', tab: p.get('tab') || 'overview', issue: p.get('issue') || '' }; }
function navigate(target: string, tab: string, issue = '') { location.hash = new URLSearchParams({ target, tab, ...(issue ? { issue } : {}) }).toString(); }
function date(s?: string) { return s ? new Date(s).toLocaleString() : 'Unavailable'; }
function Badge({ value }: { value: string }) { return <span className={`badge ${value.toLowerCase()}`}>{states[value] || value.replaceAll('_', ' ')}</span>; }

function App() {
  const [index, setIndex] = useState<Index>(); const [error, setError] = useState(''); const [r, setRoute] = useState(route());
  const [report, setReport] = useState<Report>(); const [findings, setFindings] = useState<Finding[]>([]); const [detail, setDetail] = useState<Detail>(); const [source, setSource] = useState<string[]>([]);
  const [query, setQuery] = useState(''); const [severity, setSeverity] = useState(''); const [scanner, setScanner] = useState(''); const [page, setPage] = useState(0); const [loading, setLoading] = useState(false);
  useEffect(() => { const c = new AbortController(); const refresh = () => json<Index>('data/index.json', c.signal).then(setIndex).catch(e => { if (e.name !== 'AbortError') setError(e.message); }); refresh(); const timer = window.setInterval(refresh, 60000); const change = () => setRoute(route()); window.addEventListener('hashchange', change); return () => { c.abort(); window.clearInterval(timer); window.removeEventListener('hashchange', change); }; }, []);
  const target = index?.targets.find(t => t.id === r.target) || (!r.target ? index?.targets.find(t => t.kind === 'branch' && t.branch === index.preferred_branch) || index?.targets[0] : undefined);
  useEffect(() => { setReport(undefined); setFindings([]); setDetail(undefined); setSource([]); setPage(0); setError(''); setLoading(false); if (!target?.report) return;
    const c = new AbortController(); setLoading(true); Promise.all([json<Report>(`data/${target.report}/report.json`, c.signal), json<Finding[]>(`data/${target.report}/findings.json`, c.signal)]).then(([a, b]) => { setReport(a); setFindings(b); }).catch(e => { if (e.name !== 'AbortError') setError(e.message); }).finally(() => { if (!c.signal.aborted) setLoading(false); }); return () => c.abort();
  }, [target?.id, target?.report]);
  useEffect(() => { setDetail(undefined); setSource([]); if (!r.issue || !target?.report) return; const f = findings.find(f => f.id === r.issue); if (!f) return; const c = new AbortController();
    json<Detail[]>(`data/${target.report}/details/${f.page}.json`, c.signal).then(async rows => { const d = rows.find(d => d.id === f.id); setDetail(d); if (d?.source) setSource(await json<string[]>(`data/${target.report}/${d.source}`, c.signal)); }).catch(e => { if (e.name !== 'AbortError') setError(e.message); }); return () => c.abort();
  }, [r.issue, findings, target?.report]);
  const filtered = useMemo(() => findings.filter(f => (!severity || f.severity === severity) && (!scanner || f.scanners.includes(scanner)) && `${f.message} ${f.file} ${f.rules.join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => (ranks[a.severity] ?? 9) - (ranks[b.severity] ?? 9) || a.file.localeCompare(b.file)), [findings, query, severity, scanner]);
  useEffect(() => setPage(0), [query, severity, scanner]);
  const count = Math.max(1, Math.ceil(filtered.length / 50));
  const fresh = !!report && report.analyzed_sha === target?.head_sha;
  return <><header className="topbar"><a className="brand" href="#">◈ <span>Code Analysis</span></a><span className="top-note">Current code · traceable evidence</span><a href={index ? `https://github.com/${index.analysis_repository}/actions` : 'https://github.com/combustrrr/Agentic-Kibana/actions'} target="_blank" rel="noreferrer">Workflows ↗</a></header>
    <main><section className="project"><div className="eyebrow">REPOSITORY</div><h1>{target?.repository || 'Code quality dashboard'}</h1><div className="target-row"><label htmlFor="target">Branch or pull request</label><select id="target" value={target?.id || ''} onChange={e => navigate(e.target.value, r.tab)}><option value="" disabled>Select a target</option>{['branch', 'pr'].map(kind => <optgroup key={kind} label={kind === 'branch' ? 'Branches' : 'Open pull requests'}>{index?.targets.filter(t => t.kind === kind).map(t => <option key={t.id} value={t.id}>{t.label}</option>)}</optgroup>)}</select>{target && <Badge value={target.status || 'queued'}/>}</div>
      {target?.pr && <p>Source {target.source_repository}:{target.branch} → {target.base_branch} · head analysis, not merge validation</p>}
      <div className="identity"><div><span>DISCOVERED HEAD</span><code>{target?.head_sha || 'Unavailable'}</code></div><div><span>ANALYZED COMMIT</span><code>{report?.analyzed_sha || 'Not analyzed'}</code></div><div><span>HEAD LAST CHECKED</span>{date(target?.checked_at || index?.checked_at)}</div><div><span>ANALYSIS COMPLETED</span>{date(report?.generated_at)}</div></div>
      <div className="runs">{index && <span>{index.targets.length} active targets | {index.targets.filter(t => t.status === 'queued').length} queued | {index.targets.filter(t => t.status === 'scanning').length} scanning</span>}{report?.tooling_sha && <span>Tooling <code title={report.tooling_sha}>{report.tooling_sha.slice(0, 12)}</code> | attempt {report.producer_run_attempt ?? 'Unavailable'}</span>}{report?.producer_runs.map(run => <a key={run.id} href={run.url} target="_blank" rel="noreferrer">Run #{run.id} ↗</a>)}</div>
    </section>
    {(error || index?.discovery_error || index?.publication_error || target?.error) && <div role="alert" className="notice">{error || index?.discovery_error || index?.publication_error || target?.error}</div>}
    {report && (!fresh || report.status === 'partial') && <div className="notice">{!fresh ? 'These findings belong to the older analyzed commit shown above. The newer head is not analyzed yet.' : 'Analysis is incomplete. Available findings are shown; unavailable scanners do not mean zero issues.'}</div>}
    <nav className="tabs" aria-label="Report views">{['overview', 'issues', 'scanners'].map(tab => <a key={tab} aria-current={r.tab === tab ? 'page' : undefined} href={`#${new URLSearchParams({ target: target?.id || '', tab })}`}>{tab[0].toUpperCase() + tab.slice(1)}{tab === 'issues' && report ? ` (${report.finding_count.toLocaleString()})` : ''}</a>)}</nav>
    {loading ? <p role="status" className="empty">Loading the selected report…</p> : !report ? <div className="empty"><h2>{r.target && !target ? 'Target no longer active' : 'No report available yet'}</h2><p>{target ? 'This target is waiting for analysis. Findings from another branch are never substituted.' : 'Repository discovery has not published active targets yet.'}</p></div> : <>
      {r.tab === 'overview' && <><section className="metrics">{['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].map(s => <button key={s} onClick={() => { setSeverity(s); navigate(target!.id, 'issues'); }}><span className={`dot ${s.toLowerCase()}`}/><span>{s}</span><strong>{(report.severities[s] || 0).toLocaleString()}</strong><small>reported findings</small></button>)}</section><section className="summary"><div><h2>Understand what needs attention</h2><p>{report.finding_count.toLocaleString()} findings from {report.observation_count.toLocaleString()} scanner observations. Open an issue to inspect its rule, exact location, and supporting evidence.</p><button className="primary" onClick={() => { setSeverity(''); navigate(target!.id, 'issues'); }}>Browse issues →</button></div><div><h2>Analysis coverage</h2><p>{report.channels.filter(c => ['COMPLETED', 'COMPLETED_OPTIONAL', 'CONFIGURED_COMPLETE', 'POLICY_FINDINGS'].includes(c.status)).length} of {report.channels.length} channels completed.</p><p>Strict evidence gate: <strong>{report.publication_gate.satisfied ? 'Passed' : 'Not satisfied'}</strong></p><a href={`#target=${target!.id}&tab=scanners`}>Inspect every scanner →</a></div></section></>}
      {r.tab === 'scanners' && <div className="table-scroll"><table><thead><tr><th>Scanner</th><th>Status</th><th>Findings</th><th>Workflow / evidence limitations</th></tr></thead><tbody>{report.channels.map(c => <tr key={c.channel}><td><strong>{c.name}</strong><small>{c.class}</small></td><td><Badge value={c.status}/></td><td>{c.findings === null ? 'Unavailable' : c.findings.toLocaleString()}</td><td>{c.reason || 'Retained evidence available'}<small>{c.workflow}</small></td></tr>)}</tbody></table></div>}
      {r.tab === 'issues' && <><div className="filters"><input aria-label="Search issues" placeholder="Search message, file, or rule…" value={query} onChange={e => setQuery(e.target.value)}/><select aria-label="Severity" value={severity} onChange={e => setSeverity(e.target.value)}><option value="">All severities</option>{Object.keys(ranks).map(s => <option key={s}>{s}</option>)}</select><select aria-label="Scanner" value={scanner} onChange={e => setScanner(e.target.value)}><option value="">All scanners</option>{[...new Set(findings.flatMap(f => f.scanners))].sort().map(s => <option key={s}>{s}</option>)}</select><span>{filtered.length.toLocaleString()} results</span></div><div className={detail ? 'issue-layout with-detail' : 'issue-layout'}><div className="table-scroll"><table><thead><tr><th>Severity</th><th>Issue and source</th><th>Scanner / rule</th></tr></thead><tbody>{filtered.slice(page * 50, page * 50 + 50).map(f => <tr key={f.id} className={r.issue === f.id ? 'selected' : ''}><td><Badge value={f.severity}/></td><td><button className="issue-link" onClick={() => navigate(target!.id, 'issues', f.id)}>{f.message}</button><small>{f.file}{f.line ? `:${f.line}` : ''}</small></td><td>{f.scanners.join(', ')}<small>{f.rules.join(', ')}</small></td></tr>)}</tbody></table>{!filtered.length && <p className="empty">No findings match these filters.</p>}<div className="pagination"><button disabled={page === 0} onClick={() => setPage(p => p - 1)}>Previous</button><span>Page {page + 1} of {count}</span><button disabled={page + 1 >= count} onClick={() => setPage(p => p + 1)}>Next</button></div></div>
      {detail && <aside aria-label="Issue detail"><button className="close" aria-label="Close issue" onClick={() => navigate(target!.id, 'issues')}>×</button><Badge value={detail.severity}/><h2>{detail.message}</h2><p className="path">{detail.file}:{detail.line}</p>{detail.source_url && <a href={detail.source_url} target="_blank" rel="noreferrer">Open exact source revision ↗</a>}{source.length ? <pre className="source">{source.slice(Math.max(0, detail.line - 6), Math.max(0, detail.line - 6) + 16).map((line, i) => <div key={i} className={Math.max(1, detail.line - 5) + i === detail.line ? 'highlight' : ''}><span>{Math.max(1, detail.line - 5) + i}</span>{line}</div>)}</pre> : <p className="muted">Source preview unavailable or withheld. Use the immutable source link when available.</p>}<h3>Supporting observations</h3>{detail.origins.map(o => <div className="origin" key={o.observation_id}><strong>{o.scanner_family} · {o.rule}</strong><small>{o.file}:{o.start_line}</small><small>Artifact: {o.raw_artifact || 'Unavailable'}</small></div>)}</aside>}</div></>}
    </>}
    <footer>Read-only analysis · Findings are scanner observations, not confirmed defects · Viewing this page never starts a scan.</footer></main></>;
}
createRoot(document.getElementById('root')!).render(<App/>);
