"""Generate the reusable portable producer from the existing isolated scanners."""
import json
from pathlib import Path
import yaml
from scripts.code_analysis.generate_source_workflow import generate, CHECKOUT

ROOT = Path(__file__).resolve().parents[2]
TOOLING_REPOSITORY = 'combustrrr/code-analysis-dashboard'


def reusable_source(portable=True):
    config = json.loads((ROOT / 'config/code-analysis/service.json').read_text(encoding='utf-8-sig'))
    if portable:
        config.update(profile={'mode':'portable'}, scanner_extensions=[])
    document = yaml.safe_load(generate(config))
    document['name'] = 'Reusable source analysis'
    document.pop('run-name', None)
    trigger = document.pop('on', document.pop(True, None))
    import re
    secret_names = sorted(set(re.findall(r'secrets\.([A-Z_]+)', yaml.safe_dump(document))))
    document['on'] = {'workflow_call': {'inputs':trigger['workflow_dispatch']['inputs'], 'secrets':{name:{'required':False} for name in secret_names}}}
    for job in document['jobs'].values():
        steps = []
        for step in job['steps']:
            if step.get('uses', '').startswith('actions/checkout@'):
                opts = step.setdefault('with', {})
                if opts.get('repository') != '${{ fromJSON(inputs.target).source_repository }}':
                    opts.update(repository=TOOLING_REPOSITORY, ref='${{ inputs.tooling_sha }}', **{'persist-credentials':False})
                    steps.append(step)
                    path = opts.get('path', '.')
                    steps.append({'name':'Load reviewed execution project configuration',
                        'env': {'GH_TOKEN':'${{ github.token }}', 'TOOLING_SHA':'${{ inputs.tooling_sha }}', 'TARGET_JSON':'${{ inputs.target }}', 'EXPECTED_PROFILE':'portable' if portable else 'agentic-soc'},
                        'run': f'python -I "$GITHUB_WORKSPACE/{path}/scripts/code_analysis/prepare_project.py"'})
                    continue
            if 'env' in step and 'TOOLING_SHA' in step['env']:
                step['env']['IS_REUSABLE_ANALYSIS'] = 'true'
            steps.append(step)
        job['steps'] = steps
    return '# Generated by generate_reusable_workflows.py\n' + yaml.safe_dump(document, sort_keys=False, width=110)


if __name__ == '__main__':
    (ROOT / '.github/workflows/reusable-source.yml').write_text(reusable_source(), encoding='utf-8')
    (ROOT / '.github/workflows/reusable-source-full.yml').write_text(reusable_source(False), encoding='utf-8')
