name: Code analysis source
run-name: Source analysis ${{ inputs.request_id }}
on:
  workflow_dispatch:
    inputs:
      target:
        type: string
        required: true
      tooling_sha:
        type: string
        required: true
      request_id:
        type: string
        required: true
permissions:
  contents: read
jobs:
  analyze:
    if: ${{ fromJSON(inputs.target).profile_mode == 'portable' }}
    permissions:
      contents: read
      actions: read
    uses: combustrrr/code-analysis-dashboard/.github/workflows/reusable-source.yml@514c9c09fdf7d731ae4418fe0a56dec2a0b70ae5
    with:
      tooling_sha: 514c9c09fdf7d731ae4418fe0a56dec2a0b70ae5
      target: ${{ inputs.target }}
      request_id: ${{ inputs.request_id }}
  configured-profile:
    if: ${{ fromJSON(inputs.target).profile_mode == 'agentic-soc' }}
    permissions:
      contents: read
      actions: read
    uses: combustrrr/code-analysis-dashboard/.github/workflows/reusable-source-full.yml@514c9c09fdf7d731ae4418fe0a56dec2a0b70ae5
    with:
      tooling_sha: 514c9c09fdf7d731ae4418fe0a56dec2a0b70ae5
      target: ${{ inputs.target }}
      request_id: ${{ inputs.request_id }}
