name: Code analysis source
run-name: Source analysis ${{ inputs.request_id }}
on:
  workflow_dispatch:
    inputs:
      target:
        type: string
        required: true
      tooling_sha:
        type: string
        required: true
      request_id:
        type: string
        required: true
permissions:
  contents: read
jobs:
  analyze:
    if: ${{ fromJSON(inputs.target).profile_mode == 'portable' }}
    permissions:
      contents: read
      actions: read
    uses: combustrrr/code-analysis-dashboard/.github/workflows/reusable-source.yml@df50ec7a8c40ea29818e65be5cc43ea0086ab5fb
    with:
      tooling_sha: df50ec7a8c40ea29818e65be5cc43ea0086ab5fb
      target: ${{ inputs.target }}
      request_id: ${{ inputs.request_id }}
    secrets: inherit
  configured-profile:
    if: ${{ fromJSON(inputs.target).profile_mode == 'agentic-soc' }}
    permissions:
      contents: read
      actions: read
    uses: combustrrr/code-analysis-dashboard/.github/workflows/reusable-source-full.yml@df50ec7a8c40ea29818e65be5cc43ea0086ab5fb
    with:
      tooling_sha: df50ec7a8c40ea29818e65be5cc43ea0086ab5fb
      target: ${{ inputs.target }}
      request_id: ${{ inputs.request_id }}
    secrets: inherit
